### PR TITLE
Convert from pyQT4 < 4.15 to pyQT5

### PR DESCRIPTION
**Pull request by pseiler**
* signal of EBPatcher main class was changed to match the new  style
  https://www.riverbankcomputing.com/static/Docs/PyQt4/new_style_signals_slots.html
* pyQT5 moved some classes from QtCore to QtWidgets

### CODE REVIEW

**Comment by pseiler** [comment]
Please check if I missed anything. I tested everything so far and creating patches and applying them works as intended.
But I haven't coded Qt stuff at all. This was mostly search and replace and the reworking of the signal in the EBPatcher class.

**Comment by Lyrositor** [comment]
Hey there, this was unexpected. I'm not maintaining this program anymore (I'm not sure if anybody even uses it still).

But if you can confirm you've tested this and that it all works fine, I'm happy to merge it in.

**Comment by pseiler** [comment]
Hi Lyrositor,

I found [this](https://www.romhacking.net/hacks/2518/) which is dated to 2021-11-08 and wanted to apply it, so it seems people still use it.
I tested it on openSUSE 15.3 using pyQt 5.13.1.
I clicked through every dialog and all functionality worked as expected. Only the Qt UI code needed adjustments.

**Comment by Lyrositor** [comment]
Interesting to see people are still making hacks with this! Then sure, thanks for your contribution.

**Comment by livvy94** [comment]
@Lyrositor I forget if I've reached out before but if you'd like to join a chat where everyone in the old Slack migrated to, send me a message! Lots of familiar old names and faces still active

**Comment by Lyrositor** [comment]
@vince94 Sure, shoot me a link, I might drop by.

**Comment by livvy94** [comment]
Here you go! [https://discord.gg/Dffq2HD7](https://discord.gg/Dffq2HD7)

**Pull request merged**
